/* Database schema to keep the structure of entire database. */

/* 
Create a table named animals with the following columns:
    id: integer
    name: string
    date_of_birth: date
    escape_attempts: integer
    neutered: boolean
    weight_kg: decimal
*/

CREATE TABLE animals (
    id integer generated by default as identity primary key,
    name varchar(50),
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weight_kg numeric
);

/*
    Add a column species of type string to your animals table.
*/

alter table animals add column species varchar(50);
