/* Database schema to keep the structure of entire database. */

/* 
Create a table named animals with the following columns:
    id: integer
    name: string
    date_of_birth: date
    escape_attempts: integer
    neutered: boolean
    weight_kg: decimal
*/

CREATE TABLE animals (
    id integer generated by default as identity primary key,
    name varchar(50),
    date_of_birth date,
    escape_attempts integer,
    neutered boolean,
    weight_kg numeric
);

/*
    Add a column species of type string to your animals table.
*/

alter table animals add column species varchar(50);

/*
    Create a table named owners with the following columns:
    id: integer (set it as autoincremented PRIMARY KEY)
    full_name: string
    age: integer
*/
create table owners (
    id int generated by default as identity primary key,
    full_name varchar(50),
    age smallint
);

/*
    Create a table named species with the following columns:
    id: integer (set it as autoincremented PRIMARY KEY)
    name: string
*/

create table species (
    id int generated by default as identity,
    name varchar(50),
    primary key(id)
);
